### ISSUE TITLE
Investigate StackOverflow exception occurring in production

### ISSUE THREAD

**Issue by ssawchenko** [steamclock/steamclog-android#102]
JsonObject configured like:
```
val props = JSONObject()
json.put("type", type)
json.put("product_id", productId)
json.put("is_logged_in", signedIn)
json.put("existing_tours", existingTours.map { it.productIdentifiers.appleString })
```

StackOverflow error
````
java.lang.StackOverflowError: stack size 1037KB
    at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:59)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
    at com.steamclock.steamclog.RedactableKt.getRedactedDescription(Redactable.kt:40)
```    
    
Slack convo: https://steamclock.slack.com/archives/C1EG8Q9DG/p1647022386856389

**Comment by ssawchenko** [comment]
https://steamclock.slack.com/archives/C1EG8Q9DG/p1647022386856389
